2024-06-05 09:38:00,517 INFO Watching for file changes with StatReloader 668 
2024-06-05 09:38:03,135 INFO "GET /admin/user/userinfo/ HTTP/1.1" 200 11033 212 
2024-06-05 09:38:03,189 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 09:38:05,307 INFO "GET /admin/patients/patient/ HTTP/1.1" 200 9850 212 
2024-06-05 09:38:05,353 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 09:38:05,425 INFO "GET /static/admin/img/search.svg HTTP/1.1" 200 458 212 
2024-06-05 09:38:05,478 INFO "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581 212 
2024-06-05 09:38:06,920 INFO "GET /admin/patients/patient/add/ HTTP/1.1" 200 12494 212 
2024-06-05 09:38:06,963 INFO "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586 212 
2024-06-05 09:38:06,967 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 09:38:06,972 INFO "GET /static/admin/css/forms.css HTTP/1.1" 200 9090 212 
2024-06-05 09:38:06,983 INFO "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319 212 
2024-06-05 09:38:06,999 INFO "GET /static/admin/js/calendar.js HTTP/1.1" 200 9141 212 
2024-06-05 09:38:07,007 INFO "GET /static/admin/js/change_form.js HTTP/1.1" 200 606 212 
2024-06-05 09:38:07,021 INFO "GET /static/admin/css/widgets.css HTTP/1.1" 200 11800 212 
2024-06-05 09:38:07,094 INFO "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086 212 
2024-06-05 09:38:25,259 INFO "POST /admin/patients/patient/add/ HTTP/1.1" 302 0 212 
2024-06-05 09:38:25,277 INFO "GET /admin/patients/patient/ HTTP/1.1" 200 12275 212 
2024-06-05 09:38:25,312 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 09:38:28,492 INFO "GET /admin/patients/patient/1/change/ HTTP/1.1" 200 12812 212 
2024-06-05 09:38:28,531 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 09:38:41,514 INFO "POST /admin/patients/patient/1/change/ HTTP/1.1" 302 0 212 
2024-06-05 09:38:41,548 INFO "GET /admin/patients/patient/ HTTP/1.1" 200 12278 212 
2024-06-05 09:38:41,587 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 09:39:00,761 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 09:39:01,534 INFO Watching for file changes with StatReloader 668 
2024-06-05 09:39:05,174 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 09:39:05,860 INFO Watching for file changes with StatReloader 668 
2024-06-05 09:39:10,529 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 09:39:11,333 INFO Watching for file changes with StatReloader 668 
2024-06-05 09:39:13,930 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 09:39:14,666 INFO Watching for file changes with StatReloader 668 
2024-06-05 09:39:39,379 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 09:39:40,063 INFO Watching for file changes with StatReloader 668 
2024-06-05 09:39:41,588 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 09:39:42,270 INFO Watching for file changes with StatReloader 668 
2024-06-05 09:39:43,820 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 09:39:44,553 INFO Watching for file changes with StatReloader 668 
2024-06-05 09:40:02,993 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 09:40:03,708 INFO Watching for file changes with StatReloader 668 
2024-06-05 09:41:38,106 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\serializers.py changed, reloading. 266 
2024-06-05 09:41:38,846 INFO Watching for file changes with StatReloader 668 
2024-06-05 09:41:42,488 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\serializers.py changed, reloading. 266 
2024-06-05 09:41:43,215 INFO Watching for file changes with StatReloader 668 
2024-06-05 09:43:20,794 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py changed, reloading. 266 
2024-06-05 09:43:21,469 INFO Watching for file changes with StatReloader 668 
2024-06-05 09:43:23,052 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py changed, reloading. 266 
2024-06-05 09:43:23,762 INFO Watching for file changes with StatReloader 668 
2024-06-05 09:49:45,925 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py changed, reloading. 266 
2024-06-05 09:49:48,070 INFO Watching for file changes with StatReloader 668 
2024-06-05 09:56:12,876 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 09:56:13,745 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:01:22,797 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\urls.py changed, reloading. 266 
2024-06-05 10:01:23,475 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:01:27,966 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\urls.py changed, reloading. 266 
2024-06-05 10:01:28,669 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:01:31,061 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\urls.py changed, reloading. 266 
2024-06-05 10:01:31,923 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:01:40,610 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\urls.py changed, reloading. 266 
2024-06-05 10:01:41,318 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:01:43,678 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\urls.py changed, reloading. 266 
2024-06-05 10:01:44,584 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:01:47,015 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\urls.py changed, reloading. 266 
2024-06-05 10:01:47,704 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:01:50,062 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\urls.py changed, reloading. 266 
2024-06-05 10:01:50,721 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:01:53,067 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\urls.py changed, reloading. 266 
2024-06-05 10:01:53,759 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:01:58,222 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\urls.py changed, reloading. 266 
2024-06-05 10:01:58,890 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:02:04,384 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\urls.py changed, reloading. 266 
2024-06-05 10:02:05,085 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:04:50,234 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:04:50,947 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:04:56,539 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:04:57,161 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:05:00,491 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:05:01,168 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:05:04,584 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:05:05,208 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:05:09,575 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:05:10,213 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:05:11,518 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:05:12,164 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:05:20,654 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:05:21,327 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:05:35,936 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:05:36,709 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:05:38,001 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:05:38,782 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:05:46,238 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:05:46,873 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:05:52,282 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:05:52,919 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:05:56,271 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:05:56,899 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:06:00,229 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:06:00,849 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:06:25,753 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:06:26,454 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:06:28,781 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:06:29,590 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:06:30,936 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:06:31,662 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:06:37,185 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:06:37,799 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:06:39,093 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:06:39,786 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:07:25,041 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:07:25,734 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:07:28,139 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:07:28,877 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:07:32,295 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:07:33,005 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:08:57,858 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:09:00,240 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:10:02,955 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:10:19,056 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:10:21,464 INFO "GET /admin/patients/patient/ HTTP/1.1" 200 12062 212 
2024-06-05 10:10:21,767 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 10:10:24,032 INFO "GET /admin/patients/patient/1/change/ HTTP/1.1" 200 15339 212 
2024-06-05 10:10:24,100 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 10:10:30,049 INFO "GET /admin/user/userinfo/ HTTP/1.1" 200 11033 212 
2024-06-05 10:10:30,133 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 10:10:31,904 INFO "GET /admin/auth/user/ HTTP/1.1" 200 17673 212 
2024-06-05 10:10:32,032 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 10:10:32,230 INFO "GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560 212 
2024-06-05 10:10:32,290 INFO "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097 212 
2024-06-05 10:10:53,396 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:10:53,845 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:10:54,635 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:10:55,081 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:11:05,800 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:11:06,203 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:11:07,977 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:11:09,072 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:11:10,528 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:11:11,360 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 10:11:11,816 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:11:13,213 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:11:49,520 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:11:50,004 INFO "GET /admin/auth/user/ HTTP/1.1" 200 17673 212 
2024-06-05 10:11:50,059 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 10:11:51,358 INFO "GET /admin/auth/user/ HTTP/1.1" 200 17673 212 
2024-06-05 10:11:51,485 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 10:11:58,972 INFO "GET /admin/patients/patient/ HTTP/1.1" 200 12062 212 
2024-06-05 10:11:59,022 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 10:12:00,286 INFO "GET /admin/patients/patient/1/change/ HTTP/1.1" 200 14865 212 
2024-06-05 10:12:00,368 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 10:12:08,991 INFO "POST /admin/patients/patient/1/change/ HTTP/1.1" 302 0 212 
2024-06-05 10:12:09,123 INFO "GET /admin/patients/patient/ HTTP/1.1" 200 12278 212 
2024-06-05 10:12:09,205 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 10:15:56,230 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py changed, reloading. 266 
2024-06-05 10:15:59,166 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:16:01,909 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py changed, reloading. 266 
2024-06-05 10:16:04,394 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:16:11,268 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py changed, reloading. 266 
2024-06-05 10:16:14,042 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:16:18,541 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py changed, reloading. 266 
2024-06-05 10:16:21,834 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:16:27,739 ERROR Internal Server Error: /api/get-profile/ 241 
Traceback (most recent call last):
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py", line 204, in get
    "user_id": user_data.id,
               ^^^^^^^^^^^^
AttributeError: 'UserInfo' object has no attribute 'id'
2024-06-05 10:16:27,747 ERROR "GET /api/get-profile/ HTTP/1.1" 500 94836 212 
2024-06-05 10:16:45,867 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py changed, reloading. 266 
2024-06-05 10:16:48,291 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:16:54,885 ERROR Internal Server Error: /api/get-profile/ 241 
Traceback (most recent call last):
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py", line 210, in get
    return JsonResponse(profile_data, status=status.HTTP_200_OK)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\http\response.py", line 733, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\serializers\json.py", line 106, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type builtin_function_or_method is not JSON serializable
2024-06-05 10:16:54,892 ERROR "GET /api/get-profile/ HTTP/1.1" 500 121181 212 
2024-06-05 10:16:59,293 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py changed, reloading. 266 
2024-06-05 10:17:02,654 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:17:08,301 INFO "GET /api/get-profile/ HTTP/1.1" 200 123 212 
2024-06-05 10:17:46,770 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py changed, reloading. 266 
2024-06-05 10:17:49,139 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:17:50,620 ERROR Internal Server Error: /api/get-profile/ 241 
Traceback (most recent call last):
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py", line 204, in get
    "user_id": user_data.id,
               ^^^^^^^^^^^^
AttributeError: 'UserInfo' object has no attribute 'id'
2024-06-05 10:17:50,625 ERROR "GET /api/get-profile/ HTTP/1.1" 500 94836 212 
2024-06-05 10:18:28,637 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py changed, reloading. 266 
2024-06-05 10:18:31,699 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:18:35,398 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py changed, reloading. 266 
2024-06-05 10:18:38,270 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:18:44,477 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py changed, reloading. 266 
2024-06-05 10:18:47,416 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:19:02,913 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py changed, reloading. 266 
2024-06-05 10:19:05,610 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:19:10,275 ERROR Internal Server Error: /api/get-profile/ 241 
Traceback (most recent call last):
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py", line 202, in get
    "user_id": user_data.id,
             ^^^^^^^^^^^^
AttributeError: 'UserInfo' object has no attribute 'id'
2024-06-05 10:19:10,278 ERROR "GET /api/get-profile/ HTTP/1.1" 500 94838 212 
2024-06-05 10:19:21,901 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py changed, reloading. 266 
2024-06-05 10:19:24,471 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:19:25,537 INFO "GET /api/get-profile/ HTTP/1.1" 200 108 212 
2024-06-05 10:20:55,285 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:20:57,839 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:21:01,647 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:21:04,098 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:21:09,735 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:21:12,250 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:21:16,912 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:21:19,183 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:21:23,928 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:21:26,457 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:21:33,882 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:21:37,038 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:21:39,456 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:21:41,801 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:22:14,494 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py changed, reloading. 266 
2024-06-05 10:22:16,947 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:22:33,130 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:22:36,035 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:22:44,332 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:22:46,640 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:23:09,375 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:23:13,019 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:23:39,067 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:23:42,101 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:23:54,401 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:23:57,749 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:24:16,165 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:24:18,947 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:24:34,058 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:24:37,147 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:24:41,322 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:24:44,334 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:24:46,016 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:24:48,724 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:24:52,646 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:24:55,825 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:25:01,022 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:25:03,334 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:25:19,134 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:25:21,661 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:25:33,186 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:25:35,618 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:25:37,413 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:25:39,800 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:25:44,993 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:25:48,416 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:25:57,112 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:26:00,267 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:26:04,516 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:26:06,722 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:26:17,200 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:26:19,893 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:26:24,496 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:26:27,023 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:26:31,774 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:26:34,298 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:26:38,933 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:26:41,699 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:26:51,460 ERROR Internal Server Error: /api/signup/ 241 
Traceback (most recent call last):
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\user\views.py", line 63, in signup
    username=request.data['email'],
             ~~~~~~~~~~~~^^^^^^^^^
KeyError: 'email'
2024-06-05 10:26:51,468 ERROR "POST /api/signup/ HTTP/1.1" 500 97881 212 
2024-06-05 10:27:41,141 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\urls.py changed, reloading. 266 
2024-06-05 10:27:44,334 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:27:46,540 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\urls.py changed, reloading. 266 
2024-06-05 10:27:48,859 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:28:00,973 WARNING Not Found: /api/patients/ 241 
2024-06-05 10:28:00,974 WARNING "POST /api/patients/ HTTP/1.1" 404 3516 212 
2024-06-05 10:28:08,205 WARNING Not Found: /api/patients/ 241 
2024-06-05 10:28:08,206 WARNING "POST /api/patients/ HTTP/1.1" 404 3516 212 
2024-06-05 10:28:10,674 WARNING Not Found: /api/patients 241 
2024-06-05 10:28:10,676 WARNING "POST /api/patients HTTP/1.1" 404 3513 212 
2024-06-05 10:28:40,610 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients_asse\urls.py changed, reloading. 266 
2024-06-05 10:28:43,360 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:28:47,771 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients_asse\urls.py changed, reloading. 266 
2024-06-05 10:28:50,761 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:28:57,063 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\urls.py changed, reloading. 266 
2024-06-05 10:28:59,341 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:29:06,585 WARNING Not Found: /Patients 241 
2024-06-05 10:29:06,586 WARNING "POST /Patients HTTP/1.1" 404 3428 212 
2024-06-05 10:29:10,582 WARNING Unauthorized: /patients 241 
2024-06-05 10:29:10,583 WARNING "POST /patients HTTP/1.1" 401 58 212 
2024-06-05 10:29:21,388 INFO "POST /api/login/ HTTP/1.1" 200 522 212 
2024-06-05 10:29:32,680 WARNING Bad Request: /patients 241 
2024-06-05 10:29:32,682 WARNING "POST /patients HTTP/1.1" 400 75 212 
2024-06-05 10:30:02,683 ERROR Internal Server Error: /patients 241 
Traceback (most recent call last):
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: Patient() got unexpected keyword arguments: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py", line 48, in post
    serializer.save(user=user_info_instance)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 1008, in create
    raise TypeError(msg)
TypeError: Got a `TypeError` when calling `Patient.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `Patient.objects.create()`. You may need to make the field read-only, or override the PatientsSerializer.create() method to handle this correctly.
Original exception was:
 Traceback (most recent call last):
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: Patient() got unexpected keyword arguments: 'user'

2024-06-05 10:30:02,693 ERROR "POST /patients HTTP/1.1" 500 147735 212 
2024-06-05 10:32:30,248 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:32:32,791 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:32:36,498 ERROR Internal Server Error: /patients 241 
Traceback (most recent call last):
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py", line 48, in post
    serializer.save(user=user_info_instance)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py", line 16, in create
    return super().create(validated_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 284, in __set__
    raise ValueError(
ValueError: Cannot assign "<User: admin11@gmail.com>": "Patient.created_by" must be a "UserInfo" instance.
2024-06-05 10:32:36,510 ERROR "POST /patients HTTP/1.1" 500 133398 212 
2024-06-05 10:32:48,687 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:32:51,249 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:32:53,583 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:32:55,875 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:33:09,078 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:33:11,997 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:33:12,834 ERROR Internal Server Error: /patients 241 
Traceback (most recent call last):
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py", line 48, in post
    serializer.save(user=user_info_instance)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py", line 16, in create
    return super().create(validated_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 284, in __set__
    raise ValueError(
ValueError: Cannot assign "<User: admin11@gmail.com>": "Patient.created_by" must be a "UserInfo" instance.
2024-06-05 10:33:12,859 ERROR "POST /patients HTTP/1.1" 500 133348 212 
2024-06-05 10:33:46,457 INFO "GET /admin/patients/patient/ HTTP/1.1" 200 12062 212 
2024-06-05 10:33:46,521 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 10:33:46,528 INFO "GET /static/admin/css/base.css HTTP/1.1" 304 0 212 
2024-06-05 10:33:46,528 INFO "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0 212 
2024-06-05 10:33:46,531 INFO "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0 212 
2024-06-05 10:33:46,531 INFO "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0 212 
2024-06-05 10:33:46,531 INFO "GET /static/admin/css/responsive.css HTTP/1.1" 304 0 212 
2024-06-05 10:33:46,531 INFO "GET /static/admin/css/changelists.css HTTP/1.1" 304 0 212 
2024-06-05 10:33:46,537 INFO "GET /static/admin/js/core.js HTTP/1.1" 304 0 212 
2024-06-05 10:33:46,538 INFO "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0 212 
2024-06-05 10:33:46,540 INFO "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0 212 
2024-06-05 10:33:46,540 INFO "GET /static/admin/js/actions.js HTTP/1.1" 304 0 212 
2024-06-05 10:33:46,542 INFO "GET /static/admin/js/urlify.js HTTP/1.1" 304 0 212 
2024-06-05 10:33:46,542 INFO "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0 212 
2024-06-05 10:33:46,543 INFO "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0 212 
2024-06-05 10:33:46,572 INFO "GET /static/admin/js/theme.js HTTP/1.1" 304 0 212 
2024-06-05 10:33:46,580 INFO "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0 212 
2024-06-05 10:33:46,588 INFO "GET /static/admin/js/filters.js HTTP/1.1" 304 0 212 
2024-06-05 10:33:46,595 INFO "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0 212 
2024-06-05 10:33:46,595 INFO "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0 212 
2024-06-05 10:33:47,791 INFO "GET /admin/user/userinfo/ HTTP/1.1" 200 11033 212 
2024-06-05 10:33:47,845 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 10:33:57,560 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:34:00,130 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:34:11,388 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:34:13,137 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:34:16,061 ERROR Internal Server Error: /patients 241 
Traceback (most recent call last):
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py", line 48, in post
    serializer.save(user=user_info_instance)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py", line 18, in create
    return super().create(validated_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 284, in __set__
    raise ValueError(
ValueError: Cannot assign "<User: admin11@gmail.com>": "Patient.created_by" must be a "UserInfo" instance.
2024-06-05 10:34:16,078 ERROR "POST /patients HTTP/1.1" 500 133288 212 
2024-06-05 10:34:26,701 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:34:28,394 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:34:32,729 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:34:34,666 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:34:36,584 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:34:40,350 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:34:42,797 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:34:45,745 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:34:49,199 ERROR Internal Server Error: /patients 241 
Traceback (most recent call last):
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py", line 48, in post
    serializer.save(user=user_info_instance)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py", line 18, in create
    # validated_data['created_by'] = user_info_instance.user
                                 ^^^^^^^^^^^^^^^^^^
NameError: name 'user_info_instance' is not defined
2024-06-05 10:34:49,220 ERROR "POST /patients HTTP/1.1" 500 105675 212 
2024-06-05 10:34:57,321 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:34:59,385 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:35:02,773 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:35:06,447 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:35:09,058 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:35:11,604 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:35:13,540 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:35:16,813 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:35:22,841 INFO "POST /patients HTTP/1.1" 201 74 212 
2024-06-05 10:35:29,918 INFO "GET /admin/patients/patient/ HTTP/1.1" 200 12569 212 
2024-06-05 10:35:30,074 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 10:35:30,978 INFO "GET /admin/patients/patient/ HTTP/1.1" 200 12569 212 
2024-06-05 10:35:31,043 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 10:35:33,579 INFO "GET /admin/patients/patient/2/change/ HTTP/1.1" 200 14886 212 
2024-06-05 10:35:33,629 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 10:35:33,705 INFO "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0 212 
2024-06-05 10:35:33,709 INFO "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0 212 
2024-06-05 10:35:35,477 INFO "GET /admin/patients/patient/ HTTP/1.1" 200 12569 212 
2024-06-05 10:35:37,619 INFO "GET /admin/patients/patient/1/change/ HTTP/1.1" 200 14865 212 
2024-06-05 10:35:37,664 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 10:35:39,960 INFO "GET /admin/patients/patient/ HTTP/1.1" 200 12569 212 
2024-06-05 10:35:53,770 INFO "POST /patients HTTP/1.1" 201 74 212 
2024-06-05 10:35:56,220 INFO "GET /admin/patients/patient/ HTTP/1.1" 200 13079 212 
2024-06-05 10:35:56,325 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 10:36:08,376 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:36:11,995 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:36:18,954 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:36:21,643 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:53:24,172 WARNING Not Found: /patients-record 241 
2024-06-05 10:53:24,173 WARNING "POST /patients-record HTTP/1.1" 404 3521 212 
2024-06-05 10:53:34,573 INFO "POST /patients HTTP/1.1" 201 74 212 
2024-06-05 10:54:53,977 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:54:56,917 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:54:59,815 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:55:03,286 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:55:13,143 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:55:15,445 WARNING Bad Request: /patients 241 
2024-06-05 10:55:15,445 WARNING "POST /patients HTTP/1.1" 400 132 212 
2024-06-05 10:55:21,552 INFO "POST /patients HTTP/1.1" 201 74 212 
2024-06-05 10:55:27,217 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:55:28,257 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:55:29,739 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:55:30,174 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:55:32,150 INFO "GET /admin/patients/patient/ HTTP/1.1" 200 14100 212 
2024-06-05 10:55:32,226 INFO "GET /static/admin/img/search.svg HTTP/1.1" 304 0 212 
2024-06-05 10:55:32,231 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 10:55:32,391 INFO "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0 212 
2024-06-05 10:55:38,003 INFO "POST /admin/patients/patient/ HTTP/1.1" 200 9528 212 
2024-06-05 10:55:38,169 INFO "GET /static/admin/js/cancel.js HTTP/1.1" 304 0 212 
2024-06-05 10:55:38,903 INFO "POST /admin/patients/patient/ HTTP/1.1" 302 0 212 
2024-06-05 10:55:38,930 INFO "GET /admin/patients/patient/ HTTP/1.1" 200 9988 212 
2024-06-05 10:55:38,967 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 10:55:39,033 INFO "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0 212 
2024-06-05 10:55:41,781 INFO "POST /patients HTTP/1.1" 201 74 212 
2024-06-05 10:56:31,109 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:56:31,163 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 10:56:32,640 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:56:34,154 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:56:46,866 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:56:47,639 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:56:48,648 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:56:48,965 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:56:52,600 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:56:53,360 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:56:54,390 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:56:55,577 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:59:01,601 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:59:01,677 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:59:03,250 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:59:04,796 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:59:11,211 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:59:11,721 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:59:12,581 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:59:14,717 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:59:24,239 ERROR Internal Server Error: /patients 241 
Traceback (most recent call last):
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py", line 76, in get
    patients = user_info_instance.patients.all()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UserInfo' object has no attribute 'patients'
2024-06-05 10:59:24,248 ERROR "GET /patients HTTP/1.1" 500 96804 212 
2024-06-05 10:59:41,769 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:59:41,943 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 10:59:42,978 INFO Watching for file changes with StatReloader 668 
2024-06-05 10:59:44,286 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:01:55,039 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:01:55,088 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:01:56,523 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:01:57,824 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:01:58,922 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:02:00,276 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:02:07,738 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:02:08,128 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:02:09,472 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:02:10,981 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:02:17,201 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:02:17,617 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:02:18,788 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:02:19,416 ERROR Internal Server Error: /patients 241 
Traceback (most recent call last):
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py", line 76, in get
    patients = PatientsRecord.objects.filter(created_by=user_info_instance).sort_by('-created_date')
               ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'PatientsRecord' has no attribute 'objects'
2024-06-05 11:02:19,420 ERROR "GET /patients HTTP/1.1" 500 96978 212 
2024-06-05 11:02:20,253 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:02:36,623 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:02:37,047 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:02:38,288 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:02:39,054 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:02:53,606 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:02:54,336 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:02:55,569 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:02:56,157 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:02:58,621 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:02:58,681 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:02:59,861 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:03:00,777 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:03:08,206 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:03:08,242 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:03:10,381 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:03:11,409 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:03:16,666 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:03:17,032 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:03:18,281 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:03:19,460 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:03:25,669 ERROR Internal Server Error: /patients 241 
Traceback (most recent call last):
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\coding\python\django\django-rest-framework\patient assessment system\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py", line 77, in get
    patients = Patient.objects.filter(created_by=user_info_instance).sort_by('-created_date')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'sort_by'
2024-06-05 11:03:25,677 ERROR "GET /patients HTTP/1.1" 500 96976 212 
2024-06-05 11:04:26,262 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:04:26,578 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:04:27,741 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:04:28,786 INFO "GET /patients HTTP/1.1" 200 315 212 
2024-06-05 11:04:29,827 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:06:08,388 WARNING Unauthorized: /patients 241 
2024-06-05 11:06:08,388 WARNING "POST /patients HTTP/1.1" 401 58 212 
2024-06-05 11:06:14,186 INFO "POST /patients HTTP/1.1" 201 74 212 
2024-06-05 11:06:18,099 INFO "GET /patients HTTP/1.1" 200 548 212 
2024-06-05 11:06:39,022 INFO "GET /admin/user/userinfo/ HTTP/1.1" 200 11033 212 
2024-06-05 11:06:39,129 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 11:06:41,710 INFO "GET /admin/auth/user/ HTTP/1.1" 200 17673 212 
2024-06-05 11:06:41,773 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 11:06:46,205 INFO "GET /admin/user/userinfo/ HTTP/1.1" 200 11033 212 
2024-06-05 11:06:46,331 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 11:06:47,876 INFO "GET /admin/user/userinfo/37/change/ HTTP/1.1" 200 15450 212 
2024-06-05 11:06:48,023 INFO "GET /static/admin/css/forms.css HTTP/1.1" 304 0 212 
2024-06-05 11:06:48,024 INFO "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0 212 
2024-06-05 11:06:48,036 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 11:06:48,137 INFO "GET /static/admin/css/widgets.css HTTP/1.1" 304 0 212 
2024-06-05 11:06:48,143 INFO "GET /static/admin/js/change_form.js HTTP/1.1" 304 0 212 
2024-06-05 11:06:52,265 INFO "GET /admin/user/userinfo/ HTTP/1.1" 200 11033 212 
2024-06-05 11:06:53,195 INFO "GET /admin/user/userinfo/add/ HTTP/1.1" 200 15163 212 
2024-06-05 11:06:53,244 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 11:07:10,323 INFO "POST /admin/user/userinfo/add/ HTTP/1.1" 302 0 212 
2024-06-05 11:07:10,353 INFO "GET /admin/user/userinfo/ HTTP/1.1" 200 11725 212 
2024-06-05 11:07:10,421 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 11:07:26,826 INFO "POST /api/login/ HTTP/1.1" 200 507 212 
2024-06-05 11:07:58,127 INFO "GET /patients HTTP/1.1" 200 548 212 
2024-06-05 11:08:05,489 INFO "GET /patients HTTP/1.1" 200 87 212 
2024-06-05 11:08:14,470 INFO "POST /patients HTTP/1.1" 201 74 212 
2024-06-05 11:08:18,124 INFO "GET /patients HTTP/1.1" 200 318 212 
2024-06-05 11:08:33,712 INFO "POST /api/login/ HTTP/1.1" 200 522 212 
2024-06-05 11:08:50,536 WARNING Bad Request: /patients 241 
2024-06-05 11:08:50,536 WARNING "POST /patients HTTP/1.1" 400 132 212 
2024-06-05 11:08:56,514 INFO "POST /patients HTTP/1.1" 201 74 212 
2024-06-05 11:09:03,944 INFO "GET /patients HTTP/1.1" 200 785 212 
2024-06-05 11:10:24,029 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:10:24,443 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:10:25,791 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:10:27,046 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:10:29,400 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:10:30,057 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:10:31,152 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:10:31,459 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:10:38,309 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:10:38,623 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:10:40,439 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:10:41,092 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:11:10,632 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:11:11,277 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:11:12,453 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:11:13,976 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:12:37,793 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 11:12:37,798 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 11:12:39,122 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:12:39,270 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:12:50,524 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 11:12:50,605 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 11:12:51,851 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:12:52,042 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:12:53,285 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 11:12:53,550 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\models.py changed, reloading. 266 
2024-06-05 11:12:54,817 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:12:55,880 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:15:57,943 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:16:12,512 INFO "GET /admin/user/userinfo/ HTTP/1.1" 302 0 212 
2024-06-05 11:16:12,671 INFO "GET /admin/login/?next=/admin/user/userinfo/ HTTP/1.1" 200 4186 212 
2024-06-05 11:16:12,804 INFO "GET /static/admin/css/login.css HTTP/1.1" 304 0 212 
2024-06-05 11:16:18,241 INFO "POST /admin/login/?next=/admin/user/userinfo/ HTTP/1.1" 302 0 212 
2024-06-05 11:16:18,310 INFO "GET /admin/user/userinfo/ HTTP/1.1" 200 8848 212 
2024-06-05 11:16:18,412 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 11:16:33,914 INFO "POST /api/signup/ HTTP/1.1" 201 40 212 
2024-06-05 11:16:41,365 INFO "POST /api/login/ HTTP/1.1" 200 519 212 
2024-06-05 11:16:59,747 INFO "POST /patients HTTP/1.1" 201 74 212 
2024-06-05 11:17:04,675 WARNING Unauthorized: /patients 241 
2024-06-05 11:17:04,675 WARNING "GET /patients HTTP/1.1" 401 51 212 
2024-06-05 11:17:08,514 INFO "GET /patients HTTP/1.1" 200 366 212 
2024-06-05 11:17:16,266 INFO "GET /admin/user/userinfo/ HTTP/1.1" 200 11029 212 
2024-06-05 11:17:16,396 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-06-05 11:18:48,639 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:18:49,468 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:18:50,468 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:18:51,881 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:18:54,247 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:18:54,800 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:18:55,978 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:18:57,071 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:19:08,256 INFO "GET /patients HTTP/1.1" 200 366 212 
2024-06-05 11:19:37,986 WARNING Unauthorized: /patients 241 
2024-06-05 11:19:37,986 WARNING "POST /patients HTTP/1.1" 401 58 212 
2024-06-05 11:19:50,448 WARNING Bad Request: /patients 241 
2024-06-05 11:19:50,449 WARNING "POST /patients HTTP/1.1" 400 75 212 
2024-06-05 11:20:02,171 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:20:03,158 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:20:03,490 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:20:05,313 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:20:14,495 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:20:14,636 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:20:15,812 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:20:16,814 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:20:56,551 INFO "POST /patients HTTP/1.1" 201 74 212 
2024-06-05 11:21:12,330 WARNING Bad Request: /patients 241 
2024-06-05 11:21:12,330 WARNING "PUT /patients HTTP/1.1" 400 93 212 
2024-06-05 11:21:54,968 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:21:54,984 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:21:56,887 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:21:58,155 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:22:01,927 WARNING Bad Request: /patients 241 
2024-06-05 11:22:01,927 WARNING "PUT /patients HTTP/1.1" 400 93 212 
2024-06-05 11:22:03,255 WARNING Bad Request: /patients 241 
2024-06-05 11:22:03,255 WARNING "PUT /patients HTTP/1.1" 400 93 212 
2024-06-05 11:22:23,738 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:22:24,046 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:22:25,780 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:22:26,939 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:22:27,587 WARNING Bad Request: /patients 241 
2024-06-05 11:22:27,587 WARNING "PUT /patients HTTP/1.1" 400 294 212 
2024-06-05 11:23:04,172 WARNING Bad Request: /patients 241 
2024-06-05 11:23:04,172 WARNING "PUT /patients HTTP/1.1" 400 132 212 
2024-06-05 11:23:12,855 ERROR Internal Server Error: /patients 241 
Traceback (most recent call last):
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py", line 110, in put
    patient.updated_date = datetime.now()
                           ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'
2024-06-05 11:23:12,862 ERROR "PUT /patients HTTP/1.1" 500 95701 212 
2024-06-05 11:23:31,722 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:23:31,758 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:23:33,258 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:23:34,557 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:23:35,330 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:23:36,735 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:23:40,533 WARNING Bad Request: /patients 241 
2024-06-05 11:23:40,534 WARNING "PUT /patients HTTP/1.1" 400 132 212 
2024-06-05 11:23:46,662 ERROR Internal Server Error: /patients 241 
Traceback (most recent call last):
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py", line 111, in put
    patient.updated_date = datetime.now()
                           ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
2024-06-05 11:23:46,670 ERROR "PUT /patients HTTP/1.1" 500 95875 212 
2024-06-05 11:24:04,822 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:24:04,935 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:24:06,406 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:24:08,028 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:24:08,812 WARNING Bad Request: /patients 241 
2024-06-05 11:24:08,813 WARNING "PUT /patients HTTP/1.1" 400 132 212 
2024-06-05 11:24:13,252 WARNING Unauthorized: /patients 241 
2024-06-05 11:24:13,253 WARNING "GET /patients HTTP/1.1" 401 51 212 
2024-06-05 11:24:21,945 INFO "GET /patients HTTP/1.1" 200 602 212 
2024-06-05 11:24:46,086 INFO "PUT /patients HTTP/1.1" 200 335 212 
2024-06-05 11:24:50,325 INFO "GET /patients HTTP/1.1" 200 593 212 
2024-06-05 11:25:00,081 INFO "GET /patients HTTP/1.1" 200 593 212 
2024-06-05 11:25:33,397 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:25:33,428 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:25:34,771 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:25:35,730 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:25:36,698 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:25:37,736 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:25:43,740 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:25:44,384 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:25:46,112 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:25:46,502 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:25:50,200 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:25:50,885 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:25:51,953 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:25:53,329 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:26:00,856 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:26:01,130 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:26:02,492 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:26:03,468 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:26:13,790 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:26:14,163 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:26:15,334 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:26:16,796 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:26:27,071 WARNING Bad Request: /patients 241 
2024-06-05 11:26:27,073 WARNING "PUT /patients HTTP/1.1" 400 132 212 
2024-06-05 11:26:33,287 INFO "PUT /patients HTTP/1.1" 200 338 212 
2024-06-05 11:27:12,109 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 11:27:12,125 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 11:27:13,408 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:27:14,260 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:27:17,103 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 11:27:17,275 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 11:27:18,456 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:27:19,496 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:27:21,740 ERROR Internal Server Error: /patients 241 
Traceback (most recent call last):
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py", line 106, in put
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 495, in to_internal_value
    for field in fields:
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 378, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 1079, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 1144, in get_field_names
    assert not (fields and exclude), (
AssertionError: Cannot set both 'fields' and 'exclude' options on serializer PatientsSerializer.
2024-06-05 11:27:21,748 ERROR "PUT /patients HTTP/1.1" 500 133942 212 
2024-06-05 11:28:06,993 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 11:28:07,162 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 11:28:08,462 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:28:09,666 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:28:10,523 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 11:28:12,036 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:28:14,644 ERROR Internal Server Error: /patients 241 
Traceback (most recent call last):
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py", line 106, in put
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 495, in to_internal_value
    for field in fields:
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 378, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 1079, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PREDATOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 1144, in get_field_names
    assert not (fields and exclude), (
AssertionError: Cannot set both 'fields' and 'exclude' options on serializer PatientsSerializer.
2024-06-05 11:28:14,652 ERROR "PUT /patients HTTP/1.1" 500 133937 212 
2024-06-05 11:28:19,399 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 11:28:19,961 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\serializers.py changed, reloading. 266 
2024-06-05 11:28:21,274 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:28:22,243 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:28:24,420 WARNING Bad Request: /patients 241 
2024-06-05 11:28:24,421 WARNING "PUT /patients HTTP/1.1" 400 132 212 
2024-06-05 11:28:29,363 INFO "PUT /patients HTTP/1.1" 200 340 212 
2024-06-05 11:28:40,584 INFO "GET /patients HTTP/1.1" 200 598 212 
2024-06-05 11:29:34,507 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:29:34,912 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:29:35,671 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:29:37,427 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:29:39,886 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:29:40,205 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:29:41,316 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:29:41,901 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:29:43,810 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:29:43,890 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:29:45,476 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:29:46,710 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:29:53,782 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:29:53,957 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:29:54,673 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:29:55,544 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:30:08,594 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:30:08,624 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:30:09,371 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:30:10,047 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:30:33,645 WARNING Unauthorized: /patients 241 
2024-06-05 11:30:33,646 WARNING "DELETE /patients HTTP/1.1" 401 58 212 
2024-06-05 11:30:38,116 INFO "DELETE /patients HTTP/1.1" 200 74 212 
2024-06-05 11:30:45,659 INFO "GET /patients HTTP/1.1" 200 340 212 
2024-06-05 11:30:53,824 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:30:54,465 INFO E:\coding\python\django\django-rest-framework\patient assessment system\patients_asse\patients\views.py changed, reloading. 266 
2024-06-05 11:30:55,962 INFO Watching for file changes with StatReloader 668 
2024-06-05 11:30:56,517 INFO Watching for file changes with StatReloader 668 
